apiVersion: v1
kind: Pod
metadata:
  name: bpf-map-attack
spec:
  hostPID: true
  containers:
    - name: main
      image: bpf-map-attack
      imagePullPolicy: Never
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        runAsUser: 0
        capabilities:
          add:
            - SYS_PTRACE
